tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-drivers"

cask_args appdir: "/Applications"

brew "act"
brew "asdf"
brew "bat"
brew "curl"
brew "exa"
brew "fzf"
brew "gh"
brew "go"
brew "golangci-lint"
brew "golang-migrate"
brew "jq"
brew "mas"
brew "minikube"
brew "mysql"
brew "neovim"
brew "postgresql"
brew "rsync"
brew "tfsec"
brew "vim"
brew "wget"
brew "yq"
brew "zoxide"

cask "1password"
cask "alt-tab"
cask "battle-net"
cask "deepl"
cask "discord"
cask "docker"
cask "drawio"
cask "font-hack-nerd-font"
cask "google-chrome"
cask "hstracker"
cask "jetbrains-toolbox"
cask "kindle"
cask "logi-options-plus"
cask "notion"
cask "obs"
cask "postman"
cask "raycast"
cask "slack"
cask "stoplight-studio"
cask "visual-studio-code"
cask "zoom"

mas "Spark", id: 1176895641
mas "LINE", id: 539883307
