# tap
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-drivers"

cask_args appdir: "/Applications"

# brew
brew "asdf"
brew "bat"
brew "curl"
brew "exa"
brew "fzf"
brew "go"
brew "jq"
brew "mas"
brew "neovim"
brew "rsync"
brew "starship"
brew "vim"
brew "wget"
brew "yq"
brew "zoxide"

# cask
cask "1password"
cask "alfred"
cask "deepl"
cask "discord"
cask "drawio"
cask "font-hackgen-nerd"
cask "google-chrome"
cask "google-japanese-ime"
cask "iterm2"
cask "kindle"
cask "logitech-options"
cask "microsoft-teams"
cask "notion"
cask "postman"
cask "slack"
cask "stoplight-studio"
cask "twitch"
cask "visual-studio-code"
cask "zoom"

## mas
mas "Magnet", id: 441258766
mas "Spark", id: 1176895641
mas "TweetDeck", id: 485812721
mas "LINE", id: 539883307
